### ISSUE TITLE
Move this app to the attic?

### ISSUE THREAD

**Issue by boffbowsh** [alphagov/authenticating-proxy#13]
This app is deployed in the draft stack, but hasn't had any traffic to it for 30 days in any environment. I don't believe it's actually accessible or used by anything. Does anyone know differently? Maybe @alexmuller or @heathd?

**Comment by heathd** [comment]
Sorry it's been a while since I worked on this stuff. It's quite possible that design decisions have been taken which render this not necessary. In the original design this service was an essential part of previewing things. I would expect Daniel R to know how things are now.

**Comment by boffbowsh** [comment]
Ok thanks David, I'll check with Daniel when he's next in

**Comment by boffbowsh** [comment]
@danielroseman is this still used?

**Comment by danielroseman** [comment]
This app certainly should be used; it is supposed to be protecting access-limited items from being viewed. As the name implies, it's a proxy, so all requests to the draft frontends should be going through it. If it's not receiving any traffic, that's a major concern.

**Comment by boffbowsh** [comment]
This receives traffic from Varnish on the draft-cache machines
